[package]

name = "ndarray"
version = "0.0.1"
authors = ["bluss"]
repository = "https://github.com/bluss/rust-ndarray"
documentation = "http://bluss.github.io/rust-ndarray/"

[dependencies.num]
version = "*"
features = ["complex"]
default-features = false

[dependencies.rustc-serialize]
version = "*"
optional = true

[dependencies.itertools]
version = "*"

[dependencies.serde]
version = "*"
optional = true

