[package]

name = "rendarray"
version = "0.1.0"
authors = ["bluss"]
license = "MIT/Apache-2.0"

repository = "https://github.com/bluss/rust-ndarray"
documentation = "http://bluss.github.io/rust-ndarray/"

description = "An N-dimensional array for elements of arbitrary type. Lightweight array views and slicing. The Array is copy-on-write and similar to numpy’s ndarray."

keywords = ["array", "data-structure", "n-dimensional"]

[lib]
name = "ndarray"

[dependencies.num]
version = "0.1"
features = ["complex"]
default-features = false

[dependencies.rustc-serialize]
version = "0.3"
optional = true

[dependencies.itertools]
version = "0.4"

[dependencies.serde]
version = "0.4"
optional = true


[features]

assign_ops = []
