[package]

name = "rendarray"
version = "0.2.0-alpha.6"
authors = ["bluss"]
license = "MIT/Apache-2.0"

repository = "https://github.com/bluss/rust-ndarray"
documentation = "http://bluss.github.io/rust-ndarray/"

description = "An N-dimensional array for elements of arbitrary type. Lightweight array views and slicing. Supports both uniquely owned and shared copy-on-write arrays similar to numpy’s ndarray. `rblas` is an optional dependency."

keywords = ["array", "data-structure", "multidimensional", "matrix", "blas"]

build = "build.rs"

[lib]
name = "ndarray"

[build-dependencies]
rustc_version = "0.1"

[dependencies.num]
version = "0.1"
features = ["complex"]
default-features = false

[dependencies.itertools]
version = "0.4.4"

[dependencies.rustc-serialize]
version = "0.3"
optional = true

[dependencies]
rblas = { version = "0.0.12", optional = true }

#[dependencies.serde]
#version = "0.4"
#optional = true

[features]

assign_ops = []

[profile.release]
debug = true
[profile.bench]
debug = true
